version: "3.6"
services:
  mongo:
    image: mongo:4
    container_name: xiaoju-survey-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} # 默认使用系统的环境变量
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} # 默认使用系统的环境变量
    ports:
      - "27017:27017" # 数据库端口
    volumes:
      - mongo-volume:/data/db # xiaoju-survey-data/db/data:/data/db
    networks:
      - xiaoju-survey

  xiaoju-survey:
    # 选择镜像版本：
    # slim版本 (推荐生产环境): xiaojusurvey/xiaoju-survey:1.3.4-slim
    # 完整版本 (推荐开发环境): xiaojusurvey/xiaoju-survey:1.3.4
    image: "xiaojusurvey/xiaoju-survey:1.3.4-slim" # 最新版本：https://hub.docker.com/r/xiaojusurvey/xiaoju-survey/tags
    container_name: xiaoju-survey
    restart: always
    ports:
      - "8080:8080" # API端口
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@xiaoju-survey-mongo:27017 # docker-compose 会根据容器名称自动处理
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: ${XIAOJU_SURVEY_MONGO_AUTH_SOURCE} # 如使用mongo官方镜像，并且设置了MONGO_INITDB_ROOT_USERNAME和MONGO_INITDB_ROOT_PASSWORD，默认值是admin
      AImodel_API_URL: ${AImodel_API_URL}
      AImodel_API_KEY: ${AImodel_API_KEY}
      AImodel_MODEL: ${AImodel_MODEL}
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - xiaoju-survey

volumes:
  mongo-volume:

networks:
  xiaoju-survey:
    name: xiaoju-survey
    driver: bridge
